language: python
python:  
   - "3.6"
install:  
  - pip install -e . 
  - pip install pytest-cov codecov   
# Install packages for code coverage report
script:  
  - pytest --cov=test
after_success:
  - codecov
env:
  - TOXENV=coverage
  - TOXENV=lint
  - TOXENV=s3fs
  - TOXENV=gcsfs